<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>gazebo_world_generator</name>
  <version>1.0.0</version>
  <description>LLM-based Gazebo world generator</description>

  <maintainer email="mescjim@upo.es">Miguel Escudero Jiménez</maintainer>
  <license>MIT</license>

  <author email="mescjim@upo.es">Miguel Escudero Jiménez</author>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend condition="$ROS_DISTRO == 'humble'">gazebo_ros</exec_depend>
  <exec_depend condition="$ROS_DISTRO == 'jazzy'">ros_gz_sim</exec_depend>

  <!-- Python libraries without suitable rosdep keys come from requirements.txt. -->
  <exec_depend>python3-pip</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
