FROM gwg-classic:ci
SHELL ["/bin/bash", "-c"]
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-humble-nav2-map-server && rm -rf /var/lib/apt/lists/*
COPY --from=plugin . /ws/src/gazebo_ros2_2dmap_plugin
WORKDIR /ws
RUN source /opt/ros/humble/setup.bash && \
    colcon build --packages-select gazebo_ros2_2dmap_plugin
RUN mkdir -p /root/.gazebo/models && \
    cp -a /ws/src/gazebo_world_generator/tests/fixtures/models/test_crate /root/.gazebo/models/
